version: '2'
volumes:
  db:
  staging:
  static:
  store:
services:
  django:
    image: monashmerc/mytardis_django
    build: .
    ports:
      - '8001:8000'
    environment:
      - DJANGO_ADMINS=[('MyTardis Administrator','mytardis.admin@example.com'),]
      - DJANGO_ALLOWED_HOSTS=['*']
      - DJANGO_DATETIME_FORMAT='jS F Y H:i'
      - DJANGO_DATE_FORMAT='jS F Y'
      - DJANGO_DEBUG=True
      - DJANGO_DEFAULT_FROM_EMAIL='donotreply-mytardis@example.com'
      - DJANGO_EMAIL_SUBJECT_PREFIX="[MyTardis]:"
      - DJANGO_LOG_LEVEL=INFO
      - DJANGO_SECURE_PROXY_SSL_HEADER=('HTTP_X_FORWARDED_PROTO', 'https')
      - GUNICORN_WORKER_CLASS=gevent
      - MYTARDIS_BIOFORMATS_ENABLE=False
      - MYTARDIS_NIFCERT_ENABLE=False
      - MYTARDIS_SITE_TITLE=MyTardis Demo
      - MYTARDIS_RAPID_CONNECT_ENABLED=False
    env_file:
      - env.POSTGRES
      - env.INSTITUTION
    links:
      - db
      - rabbitmq
    mem_limit: 1g
    volumes:
      - staging:/usr/src/app/var/staging
      - static:/usr/src/app/static
      - store:/usr/src/app/var/store
  celery:
    image: monashmerc/mytardis_django
    command: -A tardis.celery.tardis_app --loglevel=INFO --autoreload
    environment:
      - CELERY_ENABLE=True
      - DJANGO_LOG_LEVEL=INFO
      - MYTARDIS_BIOFORMATS_ENABLE=False
      - MYTARDIS_NIFCERT_ENABLE=False
      - DJANGO_SETTINGS_MODULE=tardis.settings
    env_file:
      - env.POSTGRES
      - env.INSTITUTION
    links:
      - db
      - rabbitmq
    mem_limit: 500m
    volumes:
      - staging:/usr/src/app/var/staging
      - store:/usr/src/app/var/store
  beat:
    image: monashmerc/mytardis_django
    command: -A tardis.celery.tardis_app
    environment:
      - CELERY_ENABLE=beat
      - MYTARDIS_BIOFORMATS_ENABLE=False
      - MYTARDIS_NIFCERT_ENABLE=False
      - DJANGO_SETTINGS_MODULE=tardis.settings
    env_file:
      - env.POSTGRES
      - env.INSTITUTION
    links:
      - db
      - rabbitmq
    mem_limit: 500m
    volumes:
      - staging:/usr/src/app/var/staging
      - store:/usr/src/app/var/store
  other:
    image: monashmerc/mytardis_django
    command: ["tail", "-f", "/dev/null",]
    environment:
      - GUNICORN_ENABLE=False
    mem_limit: 500m
    volumes:
      - staging:/usr/src/app/var/staging
      - static:/usr/src/app/static
      - store:/usr/src/app/var/store
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums --locale=en_US.utf8
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - env.POSTGRES
    mem_limit: 500m
    volumes:
      - db:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3
    mem_limit: 500m
  static:
    image: nginx
    ports:
      - '8002:80'
    restart: always
    volumes:
      - static:/usr/src/app/static/:ro
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    env_file:
      - env.NGINX
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    mem_limit: 500m
  haproxy:
    image: haproxy:1.8
    #command: echo "haproxy disabled"
    command: >
      /bin/bash -c "
      apt-get update && apt-get -y install gettext-base;
      envsubst < /usr/local/etc/haproxy/haproxy.cfg.template > /usr/local/etc/haproxy/haproxy.cfg &&
      haproxy -f /usr/local/etc/haproxy/haproxy.cfg
      "
    links:
      - django
    mem_limit: 500m
    ports:
      - '8080:8080'
      - '127.0.0.1:8443:8443'
    restart: 'no'
    volumes:
      - ./pki/localhost_chain.pem:/localhost_chain.pem
      - ./haproxy.cfg.template:/usr/local/etc/haproxy/haproxy.cfg.template
